FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY apps/worker/package*.json ./apps/worker/
COPY packages/ ./packages/
RUN npm ci
COPY apps/worker ./apps/worker
RUN npm run build -w apps/worker

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/apps/worker/dist ./apps/worker/dist
COPY --from=builder /app/apps/worker/package*.json ./apps/worker/
COPY --from=builder /app/node_modules ./node_modules
CMD ["npm", "run", "start", "-w", "apps/worker"]
